2. Experiment 2: Perform data Cleaning, smoothing, transformation, normalization.
Refer student performance dataset attached here or any suitable dataset from kaggle

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("/content/Student_Preprocessing_Dataset_50_Records.xlsx")

In [4]:
df.head()

,Student_I,Name,Gender,Age,Departme,Attendan,Marks,City
0,101.0,Amit,Male,21.0,CSE,78.0,65.0,Pune
1,102.0,Priya,Female,20.0,IT,81.0,67.0,Mumbai
2,103.0,Rahul,Male,21.0,ECE,84.0,69.0,Nashik
3,104.0,Sneha,Female,22.0,CSE,87.0,71.0,Nagpur
4,105.0,Neha,Male,23.0,IT,90.0,73.0,Kolhapur


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Student_I  43 non-null     float64
 1   Name       43 non-null     object 
 2   Gender     43 non-null     object 
 3   Age        42 non-null     float64
 4   Departme   43 non-null     object 
 5   Attendan   42 non-null     float64
 6   Marks      42 non-null     float64
 7   City       42 non-null     object 
dtypes: float64(4), object(4)
memory usage: 3.0+ KB


In [7]:
df.describe(include='all')

,Student_I,Name,Gender,Age,Departme,Attendan,Marks,City
count,43.000000,43,43,42.000000,43,42.000000,42.00000,42
unique,NaN,25,4,NaN,4,NaN,NaN,8
top,NaN,Amit,Male,NaN,CSE,NaN,NaN,Pune
freq,NaN,3,23,NaN,15,NaN,NaN,7
mean,121.651163,NaN,NaN,21.000000,NaN,86.714286,79.52381,NaN
std,12.930002,NaN,NaN,1.396861,NaN,6.314079,10.69360,NaN
min,101.000000,NaN,NaN,19.000000,NaN,78.000000,65.00000,NaN
25%,110.500000,NaN,NaN,20.000000,NaN,81.000000,71.00000,NaN
50%,122.000000,NaN,NaN,21.000000,NaN,87.000000,77.00000,NaN
75%,132.500000,NaN,NaN,22.000000,NaN,93.000000,88.50000,NaN


Check missing values

In [8]:
df.isnull().sum()

,0
Student_I,3
Name,3
Gender,3
Age,4
Departme,3
Attendan,4
Marks,4
City,4


Fill missing values

In [9]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipykernel_1315/694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)


In [14]:
df["Attendan"].fillna(df["Attendan"].mean(), inplace=True)

/tmp/ipykernel_1315/1282077833.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Attendan"].fillna(df["Attendan"].mean(), inplace=True)


In [11]:
df["Marks"].fillna(df["Marks"].mean(), inplace=True)

/tmp/ipykernel_1315/1389251290.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].mean(), inplace=True)


In [15]:
df["Departme"].fillna(df["Departme"].mode()[0], inplace=True)

/tmp/ipykernel_1315/927851582.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Departme"].fillna(df["Departme"].mode()[0], inplace=True)


In [13]:
df["City"].fillna(df["City"].mode()[0], inplace=True)

/tmp/ipykernel_1315/442806574.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0], inplace=True)


Remove duplicate records

In [16]:
print(df.duplicated().sum())

df.drop_duplicates(inplace=True)

2


Data smoothing (Bin mean)

In [18]:
df["Attendance_Bin"] = pd.cut(df["Attendan"], bins=5)

df["Attendance_Smoothed"] = (
    df.groupby("Attendance_Bin")["Attendan"]
      .transform("mean")
)

print(df[["Attendan","Attendance_Smoothed"]].head())

   Attendan  Attendance_Smoothed
0      78.0            79.153846
1      81.0            79.153846
2      84.0            84.000000
3      87.0            86.918367
4      90.0            90.000000


/tmp/ipykernel_1315/489441677.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Attendance_Bin")["Attendan"]


Label encoding

In [20]:
df["Gender"] = pd.factorize(df["Gender"])[0]
df["Departme"] = pd.factorize(df["Departme"])[0]
df["City"] = pd.factorize(df["City"])[0]

df.head()

,Student_I,Name,Gender,Age,Departme,Attendan,Marks,City,Attendance_Bin,Attendance_Smoothed
0,101.0,Amit,0,21.0,0,78.0,65.0,0,"(77.982, 81.6]",79.153846
1,102.0,Priya,1,20.0,1,81.0,67.0,1,"(77.982, 81.6]",79.153846
2,103.0,Rahul,0,21.0,2,84.0,69.0,2,"(81.6, 85.2]",84.000000
3,104.0,Sneha,1,22.0,0,87.0,71.0,3,"(85.2, 88.8]",86.918367
4,105.0,Neha,0,23.0,1,90.0,73.0,4,"(88.8, 92.4]",90.000000


In [21]:
print(df["Gender"].unique())
print(df["Departme"].unique())
print(df["City"].unique())

[0 1 2 3 4]
[0 1 2 3]
[0 1 2 3 4 5 6 7]


Min max normalization

```
xnorm = (x-xmin)/ (xmax-xmin)

```

In [23]:
df["Attendance_Normalized"] = (
    (df["Attendan"] - df["Attendan"].min()) /
    (df["Attendan"].max() - df["Attendan"].min())
)

df["Marks_Normalized"] = (
    (df["Marks"] - df["Marks"].min()) /
    (df["Marks"].max() - df["Marks"].min())
)

df[["Attendan", "Attendance_Normalized",
    "Marks", "Marks_Normalized"]].head()

,Attendan,Attendance_Normalized,Marks,Marks_Normalized
0,78.0,0.000000,65.0,0.000000
1,81.0,0.166667,67.0,0.058824
2,84.0,0.333333,69.0,0.117647
3,87.0,0.500000,71.0,0.176471
4,90.0,0.666667,73.0,0.235294


Z score standardization

```
Z =(X-u)/(alpha)
```

In [24]:
df["Age_Standardized"] = (
    (df["Age"] - df["Age"].mean()) /
    df["Age"].std()
)

df["Attendance_Standardized"] = (
    (df["Attendan"] - df["Attendan"].mean()) /
    df["Attendan"].std()
)

df["Marks_Standardized"] = (
    (df["Marks"] - df["Marks"].mean()) /
    df["Marks"].std()
)

df[["Age", "Age_Standardized",
    "Attendan", "Attendance_Standardized",
    "Marks", "Marks_Standardized"]].head()

,Age,Age_Standardized,Attendan,Attendance_Standardized,Marks,Marks_Standardized
0,21.0,0.000000,78.0,-1.413397,65.0,-1.390910
1,20.0,-0.733144,81.0,-0.926818,67.0,-1.199375
2,21.0,0.000000,84.0,-0.440238,69.0,-1.007839
3,22.0,0.733144,87.0,0.046341,71.0,-0.816304
4,23.0,1.466288,90.0,0.532920,73.0,-0.624769
